export const DROP_ELEMENT = {
    ADD_DROP_ITEM: 'ADD_DROP_ITEM',
    DISABLE_EDIT: 'DISABLE_EDIT',
    ENABLE_EDIT: 'ENABLE_EDIT',
    UPDATE_STYLE: 'UPDATE_STYLE',
    UPDATE_HEADING_TAG: 'UPDATE_HEADING_TAG',
    UPDATE_BUTTON_TYPE: 'UPDATE_BUTTON_TYPE',
    UPDATE_LINK_VALUE: 'UPDATE_LINK_VALUE',
    UPDATE_ELEMENT_TEXT: 'UPDATE_ELEMENT_TEXT',
};